#!/bin/bash
for svc in NetworkManager anacron apmd atd auditd autofs avahi-daemon avahi-dnsconfd bluetooth conman \
cpuspeed cups dnsmasq dund firstboot gpm hidd ip6tables ipmi irda kudzu lvm2-monitor mcstrans mdmonitor \
mdmpd multipathd netconsole netfs netplugd nfs nfslock nscd pand pcscd portmap psacct rawdevices rdisc \
readahead_early readahead_later restorecond rpcgssd rpcidmapd rpcsvcgssd saslauthd smartd wdaemon \
winbind wpa_supplicant ypbind vncserver;
do 
   service $svc stop;
   chkconfig --del $svc;
done
cp httpd /etc/init.d/
chkconfig --level 35 httpd on
chkconfig --list
